baseURL = "https://mt32.net/"
languageCode = "en-us"
title = "mt32.net"
theme = "mt32"

[params]
  description = "The mt32.net blog!"
  disclaimer = "The content of this website is licensed under the CC BY-NC-SA 4.0 license. No warranties apply."
  license = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
  github = "https://github.com/mtorials"
  website = "https://mtorials.de/"

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.goldmark]
    unsafe = true
